name: ASITHA-MD DEPLOY

on:
  workflow_dispatch:

jobs:
  loop-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Bot (loop & auto-restart if crash)
        run: |
          echo "Running Asitha bot in auto-restart mode..."
          timeout 18000 bash -c 'while true; do node start.js || echo "Bot crashed, restarting..."; sleep 2; done'
      - name: Re-Trigger Workflow
        if: always()
        run: |
          echo "Re-running workflow..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
  keep_alive_commit:
    runs-on: ubuntu-latest
    
    if: github.event_name == 'schedule'

    permissions:
      contents: write 
      actions: write 

    steps:
    - name: Cancel Previous Keep Alive Workflows
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ secrets.PAT_TOKEN }}

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Update asitha2.json with current timestamp
      id: update_time
      run: |
        CURRENT_TIME=$(date +%s%3N)
        echo "{\"lastActive\": \"$CURRENT_TIME\"}" > asitha2.json
        
    - name: Setup Git User
      run: |
        git config user.name "MR Asitha ❤️"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "MR Asitha ❤️: Keep Alive ping"
        token: ${{ secrets.GITHUB_TOKEN }}
